spring.config.import=optional:file:.env[.properties]

# ===========================
# DATABASE CONFIGURATION
# ===========================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===========================
# APPLICATION CONFIGURATION
# ===========================
server.port=${SERVER_PORT}

# ===========================
# GEMINI CONFIGURATION
# ===========================
gemini.api.key=${GEMINI_API_KEY}
gemini.model=${GEMINI_MODEL}

# ===========================
# JWT CONFIGURATION
# ===========================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION_MS}

logging.level.com.visume=DEBUG
logging.level.org.springframework.web=DEBUG

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.forward-headers-strategy=framework

# ===========================
# JPA / HIBERNATE CONFIGURATION
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
